# Home Assistant Development Configuration
# For FireBoard Integration Testing

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enable logging
logger:
  default: info
  logs:
    # Enable debug logging for our integration
    custom_components.fireboard: debug

# Text to speech
tts:
  - platform: google_translate

# Example automation for testing
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Developer tools
# Enable the template editor
template:

# Enable the recorder with a short purge interval for testing
recorder:
  purge_keep_days: 1
  commit_interval: 1

# Enable history
history:

# Enable the logbook
logbook:

